#!/bin/bash

cd /dehydrated

./dehydrated --register --accept-terms

if [ -z $CF_HOST ]; then
  ./dehydrated -c -t dns-01 -k 'hooks/cloudflare/hook.py'
else
  ./dehydrated -c -d $CF_HOST -t dns-01 -k 'hooks/cloudflare/hook.py'
fi

chown -R nobody:nogroup certs
chmod -R ugo+r certs
find certs -type d -exec chmod ugo+x {} \;